language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  
install:
  - pip install codecov
  - pip install .[test]

script:
  - pytest --cov=betrack --cov-report=term-missing
  
after_success:
  - codecov