version: 0.1.0.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
      HDF5_VERSION: "1.8.17"
      HDF5_VSVERSION: "10-64"
      HDF5_DIR: "C:\\hdf5\\%HDF5_VERSION%\\%HDF5_VSVERSION%"    
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""  
  - cmd: "python -m pip install --upgrade pip"
  - cmd: "pip install --upgrade setuptools"
  - if %PYTHON%=="C:\\Python34-x64" (
      appveyor DownloadFile "http://ffmpeg.org/releases/ffmpeg-4.0.tar.xz" &&
      7z x -y ffmpeg-4.0.tar.xz &&
      7z x -y ffmpeg-4.0.tar > NUL
    )
  - cmd: "pip install requests"
  - cmd: "cd C:\\projects\\betrack-cli"
  - cmd: "echo %HDF5_DIR%"
  - cmd: "python -c resources\\ci\\get_hdf5.py"
  - cmd: "pip install -e .[test]"

build: off

test_script:
  - "py.test --cov=betrack --cov-report=term-missing"

cache:
  - "%LOCALAPPDATA%\\pip\\Cache"