version: 0.0.1.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - cmd: "cd C:\\projects\\betrack-cli"
  - cmd: "pip install -e .[test]"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"