version: 0.0.1.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - cmd: "cd C:\projects\betrack-cli"
  
build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"